#include "util/get_config_path.hpp"
#include <toml++/toml.h>

#include <sys/stat.h>
#include <sys/types.h>

#include <chrono>
#include <ctime>
#include <iostream>
#include <span>

auto does_file_exist(std::string const& filename) {
  struct stat buffer;
  return (stat(filename.c_str(), &buffer) == 0);
}

auto main(int argc, const char* argv[]) -> int {
  auto args = std::span(argv, argc);
  // TODO(tybl): Replace hardcoded app name with string generated by cmake
  auto config_path = tybl::util::get_config_path("jrny");
  config_path /= "config.toml";
  auto config = toml::parse_file(config_path.native());

  // TODO(tybl): Start output with the current date/time
  auto now = std::chrono::system_clock::now();
  const std::time_t t_c = std::chrono::system_clock::to_time_t(now);
  std::cout << std::put_time(std::localtime(&t_c), "%F %T:");
  for (auto arg : args) {
    std::cout << " " << arg;
  }
  std::string filename = config["journal"]["filename"].value_or("");
  std::cout << " > " << filename << std::endl;
  return 0;
}
